create schema if not exists private;

do $$ begin
  create type public.app_role as enum ('customer', 'admin');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.order_status as enum ('pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled');
exception when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role public.app_role not null default 'customer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'آدرس من',
  recipient_name text not null,
  phone text not null,
  province text not null,
  city text not null,
  postal_code text not null,
  address_line text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null,
  english_name text not null,
  category text not null check (category in ('دیجیتال', 'اکسسوری', 'خانه و زندگی', 'مد روزمره')),
  price bigint not null check (price >= 0),
  compare_at_price bigint check (compare_at_price is null or compare_at_price >= price),
  badge text,
  accent text not null default '#153f36',
  accent_soft text not null default '#dcefe6',
  artwork text not null check (artwork in ('headphones', 'watch', 'speaker', 'bag', 'lamp', 'glasses', 'mug', 'shoe')),
  short_description text not null,
  description text not null,
  features text[] not null default '{}',
  stock integer not null default 0 check (stock >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete restrict,
  status public.order_status not null default 'pending',
  total_amount bigint not null check (total_amount >= 0),
  shipping_address jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  unit_price bigint not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  line_total bigint not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''))
  on conflict (id) do nothing;

  insert into public.user_roles (user_id, role)
  values (new.id, 'customer')
  on conflict (user_id) do nothing;
  return new;
end;
$$;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = (select auth.uid()) and role = 'admin'
  );
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure private.handle_new_user();

do $$
declare table_name text;
begin
  foreach table_name in array array['profiles', 'user_roles', 'addresses', 'products', 'orders'] loop
    execute format('drop trigger if exists set_updated_at on public.%I', table_name);
    execute format('create trigger set_updated_at before update on public.%I for each row execute procedure private.set_updated_at()', table_name);
  end loop;
end $$;

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.addresses enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Public can view active products" on public.products;
create policy "Public can view active products" on public.products for select to anon, authenticated using (is_active or (select private.is_admin()));
drop policy if exists "Admins manage products" on public.products;
create policy "Admins manage products" on public.products for all to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));

drop policy if exists "Users view own profile" on public.profiles;
create policy "Users view own profile" on public.profiles for select to authenticated using ((select auth.uid()) = id or (select private.is_admin()));
drop policy if exists "Users update own profile" on public.profiles;
create policy "Users update own profile" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

drop policy if exists "Users view own role" on public.user_roles;
create policy "Users view own role" on public.user_roles for select to authenticated using ((select auth.uid()) = user_id or (select private.is_admin()));
drop policy if exists "Admins update roles" on public.user_roles;
create policy "Admins update roles" on public.user_roles for update to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));

drop policy if exists "Users manage own addresses" on public.addresses;
create policy "Users manage own addresses" on public.addresses for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Admins view addresses" on public.addresses;
create policy "Admins view addresses" on public.addresses for select to authenticated using ((select private.is_admin()));

drop policy if exists "Users view own orders" on public.orders;
create policy "Users view own orders" on public.orders for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Admins view orders" on public.orders;
create policy "Admins view orders" on public.orders for select to authenticated using ((select private.is_admin()));
drop policy if exists "Admins update orders" on public.orders;
create policy "Admins update orders" on public.orders for update to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));

drop policy if exists "Users view own order items" on public.order_items;
create policy "Users view own order items" on public.order_items for select to authenticated using (
  exists (select 1 from public.orders where orders.id = order_items.order_id and orders.user_id = (select auth.uid()))
);
drop policy if exists "Admins view order items" on public.order_items;
create policy "Admins view order items" on public.order_items for select to authenticated using ((select private.is_admin()));

revoke all on schema private from public;
grant usage on schema private to authenticated;
revoke all on function private.is_admin() from public;
grant execute on function private.is_admin() to authenticated;

revoke all on public.profiles, public.user_roles, public.addresses, public.products, public.orders, public.order_items from anon, authenticated;
grant select on public.products to anon, authenticated;
grant select, update on public.profiles to authenticated;
grant select, update on public.user_roles to authenticated;
grant select, insert, update, delete on public.addresses to authenticated;
grant select, insert, update, delete on public.products to authenticated;
grant select, update on public.orders to authenticated;
grant select on public.order_items to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into public.products (id, slug, name, english_name, category, price, compare_at_price, badge, accent, accent_soft, artwork, short_description, description, features, stock, is_active) values
  (1, 'aura-pro-headphones', 'هدفون بی‌سیم Aura Pro', 'Aura Pro', 'دیجیتال', 2890000, 3290000, 'پرفروش', '#153f36', '#dcefe6', 'headphones', 'صدای شفاف، حذف نویز هوشمند و طراحی سبک برای تمام روز.', 'Aura Pro برای شنیدن جزئیاتی ساخته شده که معمولاً از دست می‌روند؛ با طراحی مینیمال، اتصال پایدار و بالشتک‌های نرم که در استفاده طولانی خسته‌کننده نیستند.', array['حذف نویز فعال','تا ۳۲ ساعت شارژدهی','اتصال هم‌زمان به دو دستگاه','ضمانت اصالت کالا'], 24, true),
  (2, 'nox-minimal-watch', 'ساعت مینیمال Nox', 'Nox Watch', 'اکسسوری', 1950000, null, null, '#8f4e34', '#f4dfd2', 'watch', 'فرم آرام، صفحه خوانا و بند نرم برای استفاده روزمره.', 'Nox یک ساعت بی‌زمان با جزئیات کنترل‌شده است؛ نه بیش‌ازحد رسمی و نه کاملاً اسپرت، برای کسانی که سادگی را آگاهانه انتخاب می‌کنند.', array['بدنه استیل','شیشه مقاوم','بند قابل تعویض','مقاوم در برابر پاشش آب'], 16, true),
  (3, 'mini-portable-speaker', 'اسپیکر همراه Mini', 'Mini Speaker', 'دیجیتال', 1490000, 1790000, '۱۵٪ تخفیف', '#5c477f', '#e5def1', 'speaker', 'صدای پرقدرت در ابعادی کوچک، مناسب خانه و سفر.', 'Mini با وجود ابعاد جمع‌وجور، صدایی متعادل و واضح ارائه می‌دهد و با بدنه مقاوم و باتری بادوام برای حرکت طراحی شده است.', array['صدای ۳۶۰ درجه','۱۲ ساعت شارژدهی','مقاوم در برابر آب','اتصال Bluetooth 5.3'], 31, true),
  (4, 'canvas-daily-bag', 'کیف روزمره Canvas', 'Canvas Daily', 'مد روزمره', 1180000, null, null, '#66512f', '#eae0cc', 'bag', 'سبک، جادار و مناسب رفت‌وآمدهای هر روز.', 'Canvas Daily با پارچه ضخیم، دوخت تقویت‌شده و فضای داخلی منظم، همراه ساده‌ای برای کار، دانشگاه و خریدهای روزمره است.', array['پارچه مقاوم','جیب داخلی زیپ‌دار','بند قابل تنظیم','قابل شست‌وشو'], 20, true),
  (5, 'halo-desk-lamp', 'چراغ مطالعه Halo', 'Halo Lamp', 'خانه و زندگی', 840000, null, 'جدید', '#315c67', '#dcebf0', 'lamp', 'نور گرم و قابل تنظیم برای میز کار و گوشه مطالعه.', 'Halo با نور یکنواخت و بدون لرزش، فضای کار را آرام‌تر می‌کند. بازوی قابل تنظیم آن نور را دقیقاً به جایی می‌رساند که نیاز دارید.', array['سه شدت نور','دمای رنگ گرم','مصرف انرژی پایین','بازوی قابل تنظیم'], 28, true),
  (6, 'urban-sunglasses', 'عینک آفتابی Urban', 'Urban Shade', 'اکسسوری', 1290000, 1450000, null, '#754957', '#eedcdf', 'glasses', 'فریم سبک و لنز محافظ برای روزهای روشن شهر.', 'Urban با فریم متعادل و لنزهای استاندارد UV400 طراحی شده تا بدون شلوغی بصری، استایل روزمره را کامل کند.', array['محافظت UV400','فریم سبک','لولاهای تقویت‌شده','همراه با کیف محافظ'], 18, true),
  (7, 'calm-ceramic-mug', 'ماگ سرامیکی Calm', 'Calm Mug', 'خانه و زندگی', 390000, null, null, '#4f6649', '#dfe7dc', 'mug', 'فرم دست‌ساز و لعاب مات برای لحظه‌های آرام روز.', 'Calm با حجم مناسب و دسته خوش‌فرم، برای قهوه صبح یا چای عصر ساخته شده و لعاب مات آن هر قطعه را کمی منحصربه‌فرد می‌کند.', array['سرامیک مقاوم','لعاب بدون سرب','قابل استفاده در مایکروویو','حجم ۳۵۰ میلی‌لیتر'], 42, true),
  (8, 'move-daily-shoes', 'کفش روزمره Move', 'Move Everyday', 'مد روزمره', 2480000, null, 'محبوب', '#6b6334', '#eee9c9', 'shoe', 'کفی نرم و فرم سبک برای قدم‌های طولانی روزمره.', 'Move با ترکیب رویه تنفس‌پذیر و کفی منعطف، برای حرکت پیوسته در شهر طراحی شده و ظاهر ساده آن با لباس‌های مختلف هماهنگ می‌شود.', array['رویه تنفس‌پذیر','کفی طبی نرم','زیره ضدلغزش','وزن سبک'], 14, true)
on conflict (slug) do update set
  name = excluded.name, english_name = excluded.english_name, category = excluded.category,
  price = excluded.price, compare_at_price = excluded.compare_at_price, badge = excluded.badge,
  accent = excluded.accent, accent_soft = excluded.accent_soft, artwork = excluded.artwork,
  short_description = excluded.short_description, description = excluded.description,
  features = excluded.features, stock = excluded.stock, is_active = excluded.is_active;

select setval(pg_get_serial_sequence('public.products', 'id'), greatest((select max(id) from public.products), 1));
